import localFont from 'next/font/local'
import './globals.css'


//  const Gilroy = localFont({
//   src: '../public/fonts/Gilroy-Regular.woff',
//   display: 'swap',
// })
const Lufga = localFont({
  src: '../public/fonts/Lufga Regular.woff',
  display: 'swap',
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Lufga} >{children}</body>
    </html>
  )
}
